### ISSUE TITLE
listener app failed to load class

### ISSUE THREAD

**Issue by SamMacy** [Senzing/senzing-listener#21]
Error message on step 2 of https://github.com/Senzing/senzing-listener#test-the-hello-world-app

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation

Doesn't crash the app

**Comment by barrycaceres** [comment]
This is a non-issue.  I recently resolved this in API server and will put the same fix in the next major release of Senzing-listener.  Senzing API Server had this issue for over two years.
