### ISSUE TITLE
Add initialization with G2 configuration string

### ISSUE THREAD

**Issue by oskar700** [Senzing/senzing-listener#91]
**Is your feature request related to a problem? Please describe.**
The listener initializes G2 with path to ini file. This is an issue when the listener doesn't have access to disk storage, e.g. when running as docker instance.

**Describe the solution you'd like**
Add an initialization function that takes configuration string instead of path to ini file.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by barrycaceres** [comment]
Fixed in 0.3.1 release.

**Comment by oskar700** [comment]
Fixed with #92
